### ISSUE TITLE
Serve configuration url not shown in the console

### ISSUE THREAD

**Issue by stevebeauge** [s-KaiNet/spfx-fast-serve-helpers#2] opened 2022-02-23 11:39 UTC
Hi,

This [#59](https://github.com/s-KaiNet/spfx-fast-serve/issues/59) solution is working as expected, but a small issue remains:

The console doesn't show the actual url. It's still show `?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js`.

This make more difficult to open the page in non default browser. Maybe it should show the actual url ?

Site note : maybe `--config` parameter of fast-serve should be set to `default` as default. This would follow any serve.json configuration bootstrapped by the yeoman generator by default.

Thanks

**Comment by s-KaiNet** [comment] 2022-02-23 12:39
Hi, I added serve configuration URL logging to the console. (versions `1.13.6+` and `1.14.3+`). 

For the default value for `--config` I prefer to stick with the current explicit approach, otherwise existing users might see unexpected behavior when `fast-serve` starts opening url. Imagine, that you have a few web parts and app customizer in the same solution. When developing a web part, you don't need to serve configurations, because they apply only to app and field customizers. If I add "default" serve in the mentioned case a page will be opened, which is not desired. Thus at least for the time being, I prefer the explicit `--config=name` option. 

I'm planning to re-design how fast-serve is called ([#60](https://github.com/s-KaiNet/spfx-fast-serve/issues/60)), as part of that change I will re-think what would be the best approach for handling default serve configurations. 

Please test it and tell me whether it works as expected.

**Comment by stevebeauge** [comment] 2022-02-23 13:04
> Please test it and tell me whether it works as expected.

Don't see any branch or PR. You pushed something ?

**Comment by stevebeauge** [comment] 2022-02-23 13:05
nevermind. It's in the master branch. Let met check and provide a quick feedback

**Comment by stevebeauge** [comment] 2022-02-23 15:17
I can see the comment actually, but the wrong url is still here.

Here's an attempt to solve it properly : https://github.com/s-KaiNet/spfx-fast-serve-helpers/pull/3

Regarding the `default` to be defaulted, I think the OOB serve behavior should be reproduced. It `gulp serve-deprecated` open the default configuration, `npm run serve` should do too.

**Comment by s-KaiNet** [comment] 2022-02-23 21:32
I will close this one with the comments from the related PR. Please feel free to re-open or open a new one in case of any unclearly.

**Closed by s-KaiNet** 2022-02-23 21:32 UTC
